### PR TITLE
Fix typo mentioning ES7 (should be ES6)

### PR DESCRIPTION
**Pull request by mwiens91**
Given that ES7 isn't mentioned anywhere else in the book, I'm assuming you meant to write ES6 here instead of ES7?

### CODE REVIEW

**Comment by rwieruch** [comment]
Thanks for noticing and open the PR. But this is indeed an ES7 feature https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes :)

**Comment by mwiens91** [comment]
```
// ES5
string.indexOf(pattern) !== -1

// ES6
string.includes(pattern)
```

Should the proceeding code block comment then be `// ES7` instead of `// ES6`?

**Comment by rwieruch** [comment]
Oh yes. Thanks for spotting this! Let's open another PR :)

**Comment by mwiens91** [comment]
Okay, I'll push another PR.

**Pull request closed without merging**
