### PR TITLE
V6 - Proofreading/Editing

### PR DESCRIPTION
**Pull request by rwieruch**
Final version for the next edition. 

@andres-uris @FrankFlow @GuillaumeUnice @ilasorsa @JimmyLv @juanluischaurant @lex111 @Manubi @romerorocha @sujinleeme @EmmanuelStalling It should get merged next week, but if you have any concerns, please let me know.

Previous discussion: https://github.com/the-road-to-learn-react/the-road-to-learn-react/pull/170

### CODE REVIEW

**Comment by rwieruch** [comment]
Merged version 6 🎉

**Comment by juanluischaurant** [comment]
Bravo, I like what I see over here! 🎉

**Comment by lastnamearya** [comment]
Thanks, @rwieruch now starting with the book 👍

**Comment by rwieruch** [comment]
@lastnamearya maybe you have some early feedback after reading the first chapters :)

**Pull request merged**
