### PR TITLE
Only for better reading

### PR DESCRIPTION
**Pull request by carloscarvallo**
You can see how it looks in my fork, and tell what you think

### CODE REVIEW

**Comment by rwieruch** [comment]
Cool. Didn't know about it. Does it apply for the Leanpub formatting as well or only for the GitHub markdown?

**Comment by carloscarvallo** [comment]
I don't know if applies for leanpub, if is markdown I think it would work

**Comment by rwieruch** [comment]
Okay. I will check if something changes for Leanpub. Otherwise thanks for suggesting it! I will merge it for the next edition, when everything is alright on the ebook side!

- [ ] update other chapters as well

**Comment by rwieruch** [comment]
Unfortunately it wouldn't work with the Leanpub formatting. Since this repository is used as blueprint for Leanpub, it would mess up the formatting for the books. Still, thank you for your suggestion! 👍

**Pull request closed without merging**
