### PR TITLE
`var` usage in ES6 replaced with `const`

### PR DESCRIPTION
**Pull request by ganlub**
`var` in ES6 replaced with `const` on chapter 2 and 3.

### CODE REVIEW

**Comment by rwieruch** [comment]
Hello @ganlub Thanks for your contribution! But I must say it was a conscious decision to use `var`. The variable declaration shouldn't distract from the main ES6 feature I intended to explain. That's why I kept it as `var` for the ES5 and ES6 comparisons. Did it confuse you or do you think it should be `const`? Thanks again!

**Comment by ganlub** [comment]
Hi @rwieruch thanks you for this piece of gold!
I thought you did it on purpose to not distract readers attention from the feature per se, I think it will be less confusing if `const` is used instead. I also noticed that when you talk about the spread syntax you are already using `const`.

**Comment by nyenye** [comment]
Just wanted to add my opinion as a user of these such tutorial, and say that I agree with @ganlub that it's more clear to use const and let when teaching ES6 related content, because it gives consistency to the whole subject. Being the use of const and let, one of the first things that you do/should learn in this journey, seeing them helps you identify the code as ES6. Thanks for all your hard work @rwieruch !

**Comment by rwieruch** [comment]
Thanks for your feedback @nyenye @ganlub I couldn't merge the branch unfortunately, because of conflicts. But I heard similar feedback more often now and changed it in the book. Thanks again, I am really glad that people contribute 👍 

https://github.com/rwieruch/the-road-to-learn-react/commit/fd102a4ea71be1cd2ba2f0c2c927e1fe5f6963a3

**Pull request closed without merging**
