### PR TITLE
Added missing files to folder structure

### PR DESCRIPTION
**Pull request by biancapower**
With default settings in current version of create-react-app (1.4.3) these two files are also added.

### CODE REVIEW

**Comment by rwieruch** [comment]
Yes. I thought about adding those too for the last edition. But I wasn't sure at this point. They add complexity to the whole folder structure even though they are not necessary for the ebook at all. On the other hand, readers could be confused when the two files are not listed. What do you think?

**Comment by biancapower** [comment]
That makes sense @rwieruch. Without knowing this reasoning though, as a reader, it makes the book seem "out of date" (which isn't hard in software).

I think it would be better to add the files in, but also add a brief note to the below breakdown of what each file does, something like: 

- **manifest.json** and **registerServiceWorker.js**: don't worry about what these files do at this stage, we won't be needing them in this project.

**Comment by rwieruch** [comment]
Sounds reasonable! Would you like to extend the PR or open a new one for it? Looking forward to merge it :) Thanks for your help!

**Comment by biancapower** [comment]
Done! :)

**Comment by rwieruch** [comment]
Awesome! Thank you so much! :)

**Pull request merged**
