### PR TITLE
chapter5: minor improvements

### PR DESCRIPTION
**Pull request by lex111**
I think we need to rename the variable `reverseSortedList` to something like `finalSortedList`, because the list **may not necessarily be** sorted in reverse order. (`isSortReverse ? sortedList.reverse() : sortedList`).

### CODE REVIEW

**Comment by rwieruch** [comment]
True. The same applies for the sorting, because there can be a 'NONE' sorting. So the naming would be pretty difficult then :) That's why I thought naming the list after something which might happen makes most sense. 

For the ..., look again at https://github.com/the-road-to-learn-react/the-road-to-learn-react/pull/149

The https changes are good though! Maybe we should open up a separate PR for it?

**Comment by lex111** [comment]
I reverted dots, so cancel the naming as well?

**Comment by rwieruch** [comment]
I would keep the naming like it is. But if you feel strongly about it, we can change it too :)

**Comment by lex111** [comment]
Let's change this please

**Comment by lex111** [comment]
Can we merge this? :)

**Comment by rwieruch** [comment]
The change would be missing in the other chapters and in https://github.com/the-road-to-learn-react/hackernews-client Not sure if it is worth it, because as I said, following the causes, `sortedList` would be wrong as well.

**Comment by lex111** [comment]
Left the previous naming

**Comment by rwieruch** [comment]
Thanks for your help @lex111 🎉

**Pull request merged**
