### PR TITLE
Fix for Issue #141

### PR DESCRIPTION
**Pull request by dbeckwith01**
Fix for issue #141

### CODE REVIEW

**Comment by rwieruch** [comment]
Hey @dbeckwith01 I can only see syntax fixes maybe due to Prettier? :)

**Comment by rwieruch** [comment]
You can ignore certain file extensions with your Prettier configuration. E.g.:

```
{
  "auto_format_on_save": true,
  "auto_format_on_save_excludes": [
    "*.md",
    "*.json",
  ]
}
```

Maybe you want to open a new pull request?

**Comment by lex111** [comment]
@rwieruch can I make a corrected PR?

**Comment by rwieruch** [comment]
@lex111 Yes sure 👍  Then I will close this for now.

**Pull request closed without merging**
