### PR TITLE
Change "this.state" to "this.onClickMe" in Bindings section (Chapter 2).

### PR DESCRIPTION
**Pull request by pboto**

### CODE REVIEW

**Comment by lex111** [comment]
@rwieruch what about this PR?

**Comment by rwieruch** [comment]
I think keeping it more abstract with this.state and this.props makes more sense for the big picture. What do you think? Or should the wording be different for the whole paragraph?

**Comment by lex111** [comment]
Can it be combined in any way?

**Comment by pboto** [comment]
I'd like to add the following comment:

In the first code snippet of the Bindings section, 'this.state' is initialized and 'this' is bound to the 'this.onDismiss' method in the class constructor, but 'onDismiss' does not belong to the 'state' object: it is just a property of the 'this' object.

It is true that the 'this.state' object is not accessible if 'this' is not bound but the focus here is on the 'onDismiss' event handler.

In the following code snippets the focus continues to be on the event handlers and not on the state object. So in order to keep the text consistent with the code snippets, the text should refer the event handlers and perhaps the reference to 'this.state' should be made at the end of the section, with a specific example.

However, my React knowledge is still very limited and I am willing to accept different view points and interpretations.

Thanks.

**Pull request closed without merging**
