### PR TITLE
chapter4.txt edits

### PR DESCRIPTION
**Pull request by tyleri**

### CODE REVIEW

**Comment by rwieruch** [comment]
Thank you so much @tyleri - I will release the new version today to Leanpub with your fixes 👍

**Comment by tyleri** [comment]
No problem! Thank you for the great read. I think the book really gives a good first look at React's features, and I hope more people continue to read it. 👍

**Comment by rwieruch** [comment]
After you have read it: Do you have any meta feedback where I could improve it? Or any chapters/lessons you are missing? Thanks again for your help and kind feedback :)

**Comment by tyleri** [comment]
One thing I wanted to learn more about is how to integrate React into a back-end, like Node.js. I suppose that might be too complicated for the scope of this book, however. Maybe it would be helpful to include external resources for learning how to do this at the end, though. Otherwise, I have very few complaints about the book. I really like the fact that it's open source so I was able to contribute. :)

**Pull request merged**
